plugins:
  preset-lint-consistent:
  preset-lint-markdown-style-guide:
  preset-lint-recommended:
  validate-links:
    repository: false
  # Customized settings
  lint-list-item-indent: one
  lint-maximum-line-length: 120
  lint-no-missing-blank-lines:
  lint-maximum-heading-length: 80
  lint-ordered-list-marker-value: ordered
  lint-unordered-list-marker-style: consistent
