QUERY_QUEUED = "QUEUED"
QUERY_RUNNING = "RUNNING"
QUERY_SUCCEEDED = "SUCCEEDED"
QUERY_FAILED = "FAILED"
QUERY_CANCELLED = "CANCELLED"

COMPLETED_STATES = [QUERY_SUCCEEDED, QUERY_FAILED, QUERY_CANCELLED]
SUCCESS_STATES = [QUERY_SUCCEEDED]
