from src.clients.aws_kms_client import AwsKmsClient
from tests.aws_scanner_test_case import AwsScannerTestCase
from unittest.mock import Mock, call, patch

from contextlib import redirect_stderr
from io import StringIO

from src.clients.aws_ec2_client import AwsEC2Client
from src.clients.aws_iam_client import AwsIamClient
from src.clients.aws_logs_client import AwsLogsClient
from src.data.aws_compliance_actions import ComplianceAction
from src.data.aws_scanner_exceptions import AwsScannerException

from tests import _raise, test_types_generator
from tests import test_types_generator as generator


class TestAwsComplianceActions(AwsScannerTestCase):
    def test_apply_success(self) -> None:
        client = Mock()
        action = type("TestAction", (ComplianceAction,), {"_apply": lambda s, c: self.assertEqual(c, client)})
        self.assertEqual("applied", action("something").apply(client).status)

    def test_apply_failure(self) -> None:
        client = Mock()
        action = type("TestAction", (ComplianceAction,), {"_apply": lambda s, c: _raise(AwsScannerException("boom"))})
        with redirect_stderr(StringIO()) as err:
            self.assertEqual("failed: boom", action("an_action").apply(client).status)
        self.assertIn("an_action failed: boom", err.getvalue())

    def test_delete_flow_log_action(self) -> None:
        with patch.object(AwsEC2Client, "delete_flow_logs") as delete_flow_logs:
            generator.delete_flow_log_action(flow_log_id="42")._apply(AwsEC2Client(Mock()))
        delete_flow_logs.assert_called_once_with("42")

    def test_create_flow_log_action(self) -> None:
        with patch.object(AwsEC2Client, "create_flow_logs") as create_flow_logs:
            generator.create_flow_log_action(vpc_id="8")._apply(AwsEC2Client(Mock()))
        create_flow_logs.assert_called_once_with("8", "/vpc/flow_log", "arn:aws:iam::112233445566:role/a_role")

    def test_create_flow_log_delivery_role_action(self) -> None:
        a_role = generator.role(name="vpc_flow_log_role")
        pol = a_role.policies[0]
        with patch.object(
            AwsIamClient,
            "create_role",
            side_effect=lambda n, p: a_role if n == a_role.name and p == a_role.assume_policy else None,
        ):
            with patch.object(
                AwsIamClient,
                "create_policy",
                side_effect=lambda p, d: pol if p == pol.name and d == pol.document else None,
            ):
                with patch.object(AwsIamClient, "attach_role_policy") as attach_role_policy:
                    generator.create_flow_log_delivery_role_action()._apply(AwsIamClient(Mock()))
        attach_role_policy.assert_called_once_with(a_role, pol)

    def test_delete_flow_log_delivery_role_action(self) -> None:
        client = Mock(spec=AwsIamClient)
        generator.delete_flow_log_delivery_role_action()._apply(client)
        self.assertEqual(
            [call.delete_policy("vpc_flow_log_role_policy"), call.delete_role("vpc_flow_log_role")], client.mock_calls
        )

    def test_create_central_vpc_log_group_action(self) -> None:
        with patch.object(AwsLogsClient, "create_log_group") as create_log_group:
            generator.create_vpc_log_group_action()._apply(AwsLogsClient(Mock()))
        create_log_group.assert_called_once_with("/vpc/flow_log")

    def test_delete_log_group_kms_key_alias_action(self) -> None:
        with patch.object(AwsKmsClient, "delete_alias") as delete_key:
            action = generator.delete_log_group_kms_key_alias_action()
            action._apply(client=AwsKmsClient(Mock()))

        delete_key.assert_called_once_with(name="an_alias")

    def test_create_log_group_kms_key_action(self) -> None:
        key = test_types_generator.key()
        with patch.object(AwsKmsClient, "create_key", return_value=key) as create_key:
            with patch.object(AwsKmsClient, "put_key_policy_statements") as put_key_policy_statements:
                expected_policy = [
                    {"account": key.account_id},
                    {"account": key.account_id, "region": key.region, "log_group_name": "/vpc/flow_log"},
                ]
                action = generator.create_log_group_kms_key_action()
                action._apply(client=AwsKmsClient(Mock()))

                create_key.assert_called_once_with(
                    alias="an_alias",
                    description="Autogenerated key for an_alias do not modify",
                )
                put_key_policy_statements.assert_called_once_with(key_id=key.id, statements=expected_policy)

    def test_put_central_vpc_log_group_subscription_filter_action(self) -> None:
        with patch.object(AwsLogsClient, "put_subscription_filter") as put_subscription_filter:
            generator.put_vpc_log_group_subscription_filter_action()._apply(AwsLogsClient(Mock()))
        put_subscription_filter.assert_called_once_with(
            log_group_name="/vpc/flow_log",
            filter_name="/vpc/flow_log_sub_filter",
            filter_pattern="[version, account_id, interface_id]",
            destination_arn="arn:aws:logs:::destination:central",
        )
